INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V002__create_tables.sql');

DROP TABLE WFLW_WORKFLOW_CONTENT;
DROP TABLE WFLW_WORKFLOW;

CREATE TABLE WFLW_WORKFLOW (
	ID VARCHAR(36) PRIMARY KEY, 	-- UUID
	EXTERNAL_KEY VARCHAR(200),		-- Optional external key 
	WORKFLOW_CLASS VARCHAR(200) NOT NULL,	-- Full class name corresponding to workflow
	USER_ID VARCHAR(10) DEFAULT '',  -- USER ID of user submitting the workflow
	BRANCH_ID VARCHAR(10) DEFAULT '',
	CREATION_TIME TIMESTAMP NOT NULL,
	LAST_UPDATE_TIME TIMESTAMP NOT NULL,
	METHOD VARCHAR(200) NOT NULL,
	METHOD_STARTED TIMESTAMP, 
	METHOD_ENDED TIMESTAMP,
	METHOD_EXCEPTION VARCHAR(200),
	METHOD_EXCEPTION_MESSAGE VARCHAR(2000),
	STACKTRACE clob	
) initrans 8;

CREATE TABLE WFLW_WORKFLOW_CONTENT (
	ID VARCHAR(36) PRIMARY KEY,	
	CONTENT blob,
	FOREIGN KEY (ID) REFERENCES WFLW_WORKFLOW(ID)
) initrans 32;

CREATE INDEX WFLW_DOCUMENT_IX1 ON WFLW_WORKFLOW(USER_ID);
CREATE INDEX WFLW_DOCUMENT_IX2 ON WFLW_WORKFLOW(BRANCH_ID);
CREATE INDEX WFLW_DOCUMENT_IX3 ON WFLW_WORKFLOW(CREATION_TIME);
CREATE INDEX WFLW_DOCUMENT_IX4 ON WFLW_WORKFLOW(LAST_UPDATE_TIME);
