INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V003__workflow_history.sql');

DROP TABLE WFLW_WORKFLOW_HISTORY;

CREATE TABLE WFLW_WORKFLOW_HISTORY (
	ID VARCHAR(36) NOT NULL,	
	METHOD VARCHAR(200) NOT NULL,
	METHOD_STARTED TIMESTAMP NOT NULL, 
	METHOD_ENDED TIMESTAMP NOT NULL,
	METHOD_EXCEPTION VARCHAR(200),
	METHOD_EXCEPTION_MESSAGE VARCHAR(2000),
	STACKTRACE clob,
	FOREIGN KEY (ID) REFERENCES WFLW_WORKFLOW(ID)
);

CREATE INDEX WFLW_HISTORY_IX1 ON WFLW_WORKFLOW_HISTORY(ID);
