INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V004__create_nds_tables.sql');

DROP TABLE WFLW_NDS_EVENT;

CREATE TABLE WFLW_NDS_EVENT (
	ID varchar(36), 	
	EVENT_TIMESTAMP timestamp, -- time when event was received from NDS and stored.	 		
	CONTENT blob,	
	USER_ID varchar(50),
	APPLICATION_ID varchar(50),
	TECHNICAL_USER_ID varchar(50),
	REQUEST_ID varchar(100),
	REQUEST_DOMAIN varchar(3),
	SESSION_ID varchar(200),
	EVENT_OCCURED timestamp,
	EVENT_REPORTED timestamp,
	DOCUMENT_URI varchar(200),
	EVENT varchar(50),
	MESSAGE varchar(2000),	
	primary key (ID)	 			
);

CREATE INDEX WFLW_NDS_EVENT_IX1 ON WFLW_NDS_EVENT(USER_ID);
CREATE INDEX WFLW_NDS_EVENT_IX2 ON WFLW_NDS_EVENT(SESSION_ID);
CREATE INDEX WFLW_NDS_EVENT_IX3 ON WFLW_NDS_EVENT(REQUEST_ID);
CREATE INDEX WFLW_NDS_EVENT_IX4 ON WFLW_NDS_EVENT(EVENT_OCCURED);
CREATE INDEX WFLW_NDS_EVENT_IX5 ON WFLW_NDS_EVENT(EVENT_TIMESTAMP);

DROP TABLE WFLW_ARCHIVED_NDS_EVENT;

CREATE TABLE WFLW_ARCHIVED_NDS_EVENT (
	ID varchar(36),	
	EVENT_TIMESTAMP timestamp, -- time when event was received from NDS and stored.	 		
	CONTENT blob,	
	SESSION_ID varchar(200),
	primary key (ID)
);
