INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V006__workflow_metadata.sql');

DROP TABLE WFLW_METADATA;
DROP TABLE WFLW_PROPERTYTYPE;

CREATE TABLE WFLW_PROPERTYTYPE (
	ID INT PRIMARY KEY,	
	NAME VARCHAR(100) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(300) 	
);

CREATE TABLE WFLW_METADATA (
	WORKFLOW_ID VARCHAR(36) NOT NULL,
	PROPERTY_ID INT NOT NULL,
	VALUE VARCHAR(200) NOT NULL,	 	
 	FOREIGN KEY (WORKFLOW_ID) REFERENCES WFLW_WORKFLOW(ID)
);

ALTER TABLE WFLW_METADATA ADD FOREIGN KEY (PROPERTY_ID) REFERENCES WFLW_PROPERTYTYPE(ID);

CREATE INDEX WFLW_METADATA_IX ON
WFLW_METADATA(PROPERTY_ID, VALUE);




