INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V007__server_version.sql');

ALTER TABLE WFLW_WORKFLOW ADD SERVERNAME VARCHAR(30);
ALTER TABLE WFLW_WORKFLOW ADD VERSION VARCHAR(30);

ALTER TABLE WFLW_WORKFLOW_HISTORY ADD SERVERNAME VARCHAR(30);
ALTER TABLE WFLW_WORKFLOW_HISTORY ADD VERSION VARCHAR(30);