INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V008__workflow_controller.sql');

DROP TABLE WFLW_WORKFLOW_CONTROLLER;

CREATE TABLE WFLW_WORKFLOW_CONTROLLER (
	ID VARCHAR(36) PRIMARY KEY,	
	CONTROLLER blob,
	FOREIGN KEY (ID) REFERENCES WFLW_WORKFLOW(ID)
);




