INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V009__workflow_config.sql');

DROP TABLE WFLW_WORKFLOW_CLASS_SERVER;

CREATE TABLE WFLW_WORKFLOW_CLASS_SERVER (
	WORKFLOW_CLASS VARCHAR(200) NOT NULL,	-- Full class name corresponding to workflow	
	SERVERNAME VARCHAR(30) NOT NULL,
	ENABLED SMALLINT DEFAULT 1 NOT NULL,
	primary key (WORKFLOW_CLASS, SERVERNAME) 
);




