INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V010__add_server_version_to_archive.sql');

ALTER TABLE WFLW_ARCHIVED_WORKFLOW ADD START_WHEN TIMESTAMP;   
ALTER TABLE WFLW_ARCHIVED_WORKFLOW ADD SERVERNAME VARCHAR(30);
ALTER TABLE WFLW_ARCHIVED_WORKFLOW ADD VERSION VARCHAR(30);

DROP TABLE WFLW_ARCHIVED_WORKFLOW_CONTENT;

CREATE TABLE WFLW_ARCHIVED_WORKFLOW_CONTENT (
	ID VARCHAR(36) PRIMARY KEY,	
	CONTENT blob,
	FOREIGN KEY (ID) REFERENCES WFLW_ARCHIVED_WORKFLOW(ID)
);

DROP TABLE WFLW_ARCHIVED_WORKFLOW_HISTORY;

CREATE TABLE WFLW_ARCHIVED_WORKFLOW_HISTORY (
	ID VARCHAR(36) NOT NULL,	
	METHOD VARCHAR(200) NOT NULL,
	METHOD_STARTED TIMESTAMP NOT NULL, 
	METHOD_ENDED TIMESTAMP NOT NULL,
	METHOD_EXCEPTION VARCHAR(200),
	METHOD_EXCEPTION_MESSAGE VARCHAR(2000),
	STACKTRACE clob,
	SERVERNAME VARCHAR(30),
	VERSION VARCHAR(30),
	FOREIGN KEY (ID) REFERENCES WFLW_ARCHIVED_WORKFLOW(ID)
);