INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V012__incr_field_sizes.sql');

ALTER TABLE WFLW_WORKFLOW MODIFY SERVERNAME VARCHAR(255);
ALTER TABLE WFLW_WORKFLOW MODIFY VERSION VARCHAR(255);

ALTER TABLE WFLW_WORKFLOW_HISTORY MODIFY SERVERNAME VARCHAR(255);
ALTER TABLE WFLW_WORKFLOW_HISTORY MODIFY VERSION VARCHAR(255);

ALTER TABLE WFLW_ARCHIVED_WORKFLOW MODIFY SERVERNAME VARCHAR(255);
ALTER TABLE WFLW_ARCHIVED_WORKFLOW MODIFY VERSION VARCHAR(255);

ALTER TABLE WFLW_ARCHIVED_WORKFLOW_HISTORY MODIFY SERVERNAME VARCHAR(255);
ALTER TABLE WFLW_ARCHIVED_WORKFLOW_HISTORY MODIFY VERSION VARCHAR(255);
