INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V014_add_request_domain_to_workflow.sql');

ALTER TABLE WFLW_WORKFLOW ADD REQUEST_DOMAIN VARCHAR2(255 CHAR);
ALTER TABLE WFLW_ARCHIVED_WORKFLOW ADD REQUEST_DOMAIN VARCHAR2(255 CHAR);