INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V016__add_label.sql');

CREATE TABLE WFLW_LABEL (
	ID VARCHAR(36) PRIMARY KEY, 	-- UUID
	CREATION_TIME TIMESTAMP NOT NULL,
	EXPIRE_TIME TIMESTAMP,
	CREATED_BY VARCHAR(10) NOT NULL, 	
	NAME VARCHAR(100) UNIQUE NOT NULL,
	IGNORE_WORKFLOWS INT DEFAULT 0, 
	DESCRIPTION VARCHAR(300) 	
);

CREATE INDEX WFLW_LABEL_IX1 ON WFLW_LABEL(CREATED_BY);
CREATE INDEX WFLW_LABEL_IX2 ON WFLW_LABEL(EXPIRE_TIME);
CREATE INDEX WFLW_LABEL_IX3 ON WFLW_LABEL(CREATION_TIME);

ALTER TABLE WFLW_WORKFLOW ADD LABEL VARCHAR2(36);
ALTER TABLE WFLW_WORKFLOW ADD FOREIGN KEY(LABEL) REFERENCES WFLW_LABEL(ID);

ALTER TABLE WFLW_ARCHIVED_WORKFLOW ADD LABEL VARCHAR2(36); -- Foreign key constraint removed from archived flow.



