INSERT INTO WFLW_VERSION (SCRIPT) 
VALUES ('V020__add_missing_index.sql');

DROP INDEX WFLW_WORKFLOW_INDEX1;
CREATE INDEX WFLW_WORKFLOW_INDEX1 ON WFLW_WORKFLOW(EXTERNAL_KEY,1);

DROP INDEX WFLW_WORKFLOW_INDEX2;
CREATE INDEX WFLW_WORKFLOW_INDEX2 ON WFLW_WORKFLOW(WORKFLOW_CLASS);

DROP INDEX WFLW_WORKFLOW_INDEX3;
CREATE INDEX WFLW_WORKFLOW_INDEX3 ON WFLW_WORKFLOW(METHOD);

