INSERT INTO WFLW_VERSION (SCRIPT)
VALUES ('V025_performance_improvements.sql');

ALTER TABLE WFLW_WORKFLOW ADD IS_PICKED NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE WFLW_WORKFLOW MODIFY (START_WHEN TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DROP INDEX WFLW_WORKFLOW_IX14;
CREATE INDEX WFLW_WORKFLOW_IX14 ON WFLW_WORKFLOW(WORKFLOW_CLASS, START_WHEN, IS_PICKED) INITRANS 10;

DROP INDEX WFLW_WORKFLOW_IX15;
CREATE INDEX WFLW_WORKFLOW_IX15 ON WFLW_WORKFLOW(WORKFLOW_CLASS, EVENTS_QUEUED) INITRANS 10;

-- Get rid of index which we no longer need
DROP INDEX WFLW_WORKFLOW_INDEX1;
DROP INDEX WFLW_WORKFLOW_INDEX2;
DROP INDEX WFLW_WORKFLOW_INDEX3;

DROP INDEX WFLW_DOCUMENT_IX1;
DROP INDEX WFLW_DOCUMENT_IX2;
DROP INDEX WFLW_DOCUMENT_IX3;
DROP INDEX WFLW_DOCUMENT_IX4;

DROP INDEX WFLW_WORKFLOW_IX5;
DROP INDEX WFLW_WORKFLOW_IX6;
DROP INDEX WFLW_WORKFLOW_IX7;
DROP INDEX WFLW_WORKFLOW_IX8;
DROP INDEX WFLW_WORKFLOW_IX9;
DROP INDEX WFLW_WORKFLOW_IX10;
DROP INDEX WFLW_WORKFLOW_IX11;
DROP INDEX WFLW_WORKFLOW_IX12;
DROP INDEX WFLW_WORKFLOW_IX13;

update wflw_workflow set start_when = sysdate where start_when=null;
