INSERT INTO WFLW_VERSION (SCRIPT)
VALUES ('V026__alter-start_when.sql');

update WFLW_WORKFLOW set START_WHEN=CREATION_TIME
where START_WHEN is null;

alter session set DDL_LOCK_TIMEOUT=60;
ALTER TABLE WFLW_WORKFLOW MODIFY (START_WHEN NOT NULL);
