DELETE FROM WFLW_VERSION where SCRIPT='V016__add_label.sql';

ALTER TABLE WFLW_WORKFLOW DROP COLUMN LABEL;
ALTER TABLE WFLW_ARCHIVED_WORKFLOW DROP COLUMN LABEL;

DROP INDEX WFLW_LABEL_IX1;
DROP INDEX WFLW_LABEL_IX2;
DROP INDEX WFLW_LABEL_IX3;

DROP TABLE WFLW_LABEL;


