INSERT INTO EDMS_VERSION (SCRIPT) 
VALUES ('V002__create_tables.sql');

--DROP TABLE EDMS_METADATA;
--DROP TABLE EDMS_DOCUMENT;
--DROP TABLE EDMS_ARCHIVE;
--DROP TABLE EDMS_PROPERTYTYPE;

CREATE TABLE EDMS_PROPERTYTYPE (
	ID INT PRIMARY KEY,	
	NAME VARCHAR(100) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(300) 	
);

CREATE TABLE EDMS_ARCHIVE (
	ID INT PRIMARY KEY,					-- Id
	NAME VARCHAR(100) UNIQUE NOT NULL,  -- Unique name of archive
	URL_TEMPLATE VARCHAR(200) 	
);

CREATE TABLE EDMS_DOCUMENT (
	ID VARCHAR(36) PRIMARY KEY, 	-- UUID
	KEY VARCHAR(200) NOT NULL, 			-- Foreign key to document archive
	ARCHIVE_ID INT NOT NULL,			-- Identification (i.e. URL) for source archive where document is stored  	
	NAME VARCHAR(200) NOT NULL,	-- Name of document
	USER_ID VARCHAR(10) DEFAULT '',
	ARCHIVAL_TIME TIMESTAMP NOT NULL,
	GENERATION_TIME TIMESTAMP,
	FOREIGN KEY (ARCHIVE_ID) REFERENCES EDMS_ARCHIVE(ID) 
);

CREATE TABLE EDMS_METADATA (
	DOCUMENT_ID VARCHAR(36) NOT NULL,
	PROPERTY_ID INT NOT NULL,
	VALUE VARCHAR(100) NOT NULL,	 	
 	FOREIGN KEY (DOCUMENT_ID) REFERENCES EDMS_DOCUMENT(ID)	
);

ALTER TABLE EDMS_METADATA ADD FOREIGN KEY (PROPERTY_ID) REFERENCES EDMS_PROPERTYTYPE(ID)

CREATE INDEX EDMS_METADATA_IX ON
EDMS_METADATA(PROPERTY_ID, VALUE);




